---
title: "Data Wrangling ii"
output: github_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(p8105.datasets)
library(rvest)
library(httr)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

##Scrape a table

I want the first table from this page:(https://samhda.s3-us-gov-west-1.amazonaws.com/s3fs-public/field-uploads/2k15StateFiles/NSDUHsaeShortTermCHG2015.htm) 

read in the html

```{r}
url= "https://samhda.s3-us-gov-west-1.amazonaws.com/s3fs-public/field-uploads/2k15StateFiles/NSDUHsaeShortTermCHG2015.htm"

drug_use_html = read_html(url)
drug_use_html
```

extrace the table(s)

```{r}
table_marj=
drug_use_html |> 
  html_table() |> 
  first() |> 
  slice(-1)

table_marj
```

## Learning Assessment

```{r}
nyc_cost = 
  read_html("https://www.bestplaces.net/cost_of_living/city/new_york/new_york") |> 
  html_table(header=TRUE) |> 
  first()
```


## CSS Selectos for Star Wars Movies

currently website down but same idea

```{r}
swm_html=
  read_html("https://dorksideoftheforce.com/all-star-wars-movies-ranked-by-rotten-tomatoes-score")

title_vec=
  swm_html |> 
  html_elements("em strong") |> 
  html_text()

rating_vec=
  swm_html |> 
  html_elements("strong:nth-child(3)") |> 
  html_text()

```



















